# coding=utf-8

RTV_url_dict = {"Telewizory": "telewizory-led-lcd-plazmowe", "Zestawy kina domowego": "zestawy-kina-domowego1",
                "Soundbary": "soundbar-speakerbar", "Amplitunery": "amplitunery", "Zestawy kolumn": "zestawy-kolumn",
                "Subwoofery": "subwoofery", "Odtwarzacze Blu-ray": "odtwarzacze-blu-ray",
                "Odtwarzacze DVD": "odtwarzacze-dvd", "Odtwarzacze multimedialne": "odtwarzacze-multimedialne",
                "Przenośne DVD": "przenosne-odtwarzacze-dvd", "Radia samochodowe": "radioodtwarzacze-samochodowe",
                "Głośniki samochodowe": "glosniki-samochodowe", "Wzmacniacze samochodowe": "wzmacniacze-samochodowe",
                "Radia CB": "radia-cb", "Anteny CB": "anteny-cb", "Wieże": "zestawy-muzyczne",
                "Wzmacniacze": "wzmacniacze", "Odtwarzacze CD": "odtwarzacze-cd", "Kolumny audio": "kolumny-stereo",
                "Głośniki centralne": "glosniki-centralne", "Głośniki przenośne": "glosniki-przenosne",
                "Uchwyty głośnikowe": "uchwyty-glosnikowe",
                "Systemy audio i aktywne głośniki BT": "stacje-dokujace-ipod-iphone",
                "Systemy multiroom": "systemy-muzyczne", "Gramofony": "gramofony", "Kontrolery DJ": "kontrolery-dj",
                "Power Audio": "zestawy-muzyczne,g!zestaw-power-audio",
                "Odtwarzacze MP3/MP4/iPod": "ipod-odtwarzacze-mp3-mp4",
                "Radioodtwarzacze CD": "radioodtwarzacze-cd", "Radioodbiorniki": "radioodbiorniki",
                "Radiobudziki": "radiobudziki", "Dyktafony cyfrowe": "dyktafony-cyfrowe",
                "Słuchawki douszne": "sluchawki,typ!douszne",
                "Słuchawki nauszne": "sluchawki,typ!nauszne",
                "Słuchawki bezprzewodowe": "sluchawki,g!sluchawki-bezprzewodowe",
                "Słuchawki sportowe": "sluchawki,przeznaczenie!sportowe",
                "Wzmacniacze słuchawkowe": "wzmacniacze-sluchawkowe",
                "Uchwyty do telewizorów": "uchwyty-do-telewizorow,a1:2", "Okulary 3D": "okulary-3d",
                "Adaptery Wi-Fi i Bluetooth": "transmisja-audio-wideo-wifi", "Anteny": "anteny",
                "Przedłużacze sieciowe": "przedluzacze-sieciowe", "Piloty uniwersalne": "piloty-uniwersalne",
                "Baterie": "baterie", "Adaptery i przejściówki": "adaptery-i-przejsciowki", "Latarki": "latarki",
                "Produkty czyszczące": "produkty-czyszczace,przeznaczenie_2!rtv", "Stoliki RTV": "stoliki",
                "Tunery DVB-T": "tunery-dvb-t", "Tunery DVB-S": "tunery-telewizji-satelitarnej",
                "Akcesoria do tunerów satelitarnych": "akcesoria-do-tunerow-satelitarnych",
                "Wtyki, złączki, gniazda": "wtyki-zlaczki-gniazda1", "Rozdzielacze sygnału": "rozdzielacze-sygnalu1"}

AGD_url_dict = {"Pralki": "pralki", "Suszarki": "suszarki", "Pralki wirnikowe i wirówki": "pralki-wirnikowe-i-wirowki",
                "Pralko-suszarki": "pralko-suszarki", "Lodówki": "lodowki", "Zamrażarki": "zamrazarki",
                "Chłodziarki do wina": "chlodziarki-do-wina", "Witryny i szafy profesjonalne": "witryny-chlodnicze",
                "Lodówki turystyczne": "Lodowki-turystyczne", "Kuchnie": "kuchnie",
                "Kuchnie nastawne": "kuchnie-nastawne", "Okapy": "okapy", "Zmywarki": "zmywarki",
                "Kuchenki mikrofalowe": "kuchenki-mikrofalowe", "Zlewozmywaki": "zlewozmywaki",
                "Baterie kuchenne": "baterie-kuchenne", "Sortowniki odpadów": "sortowniki-odpadow",
                "Dozowniki do mydła": "dozowniki-do-mydla", "Filtry do okapów": "filtry-do-okapow",
                "Wyposażenie do pralek i suszarek": "wyposazenie-do-pralek-i-suszarek",
                "Produkty do zmywarek": "produkty-do-zmywarek", "Produkty do lodówek": "produkty-do-lodowek",
                "Produkty czyszczące": "produkty-czyszczace5,h1", "Garnki i czajniki": "garnki-i-czajniki",
                "Patelnie": "patelnie1", "Pojemniki": "pojemniki",
                "Węże go gazu": "weze-do-gazu", "Węże do wody": "weze-do-wody"}

AGD_zabudowa_url_dict = {"Piekarniki do zabudowy": "piekarniki-do-zabudowy", "Płyty do zabudowy": "plyty-do-zabudowy",
                         "Zmywarki do zabudowy": "zmywarki-do-zabudowy",
                         "Kuchenki mikrofalowe do zabudowy": "kuchenki-mikrofalowe-do-zabudowy",
                         "Okapy do zabudowy": "okapy-do-zabudowy", "Kuchnie do zabudowy": "kuchnie-do-zabudowy",
                         "Ekspresy do zabudowy": "ekspresy-do-zabudowy",
                         "Urządzenia do gotowania na parze": "urzadzenia-do-gotowania-na-parze",
                         "Lodówki do zabudowy": "lodowki-do-zabudowy",
                         "Zamrażarki do zabudowy": "zamrazarki-do-zabudowy", "Pralki do zabudowy": "pralki-do-zabudowy",
                         "Pralko-suszarki do zabudowy": "pralko-suszarki-do-zabudowy", "Zlewozmywaki": "zlewozmywaki",
                         "Baterie kuchenne": "baterie-kuchenne", "Sortowniki odpadów": "sortowniki-odpadow",
                         "Dozowniki do mydła": "dozowniki-do-mydla"}

AGD_male_url_dict = {"Odkurzacze": "odkurzacze", "Odkurzacze automatyczne": "odkurzacze-automatyczne",
                     "Żelazka": "zelazka", "Stacje pary": "zelazka-systemowe", "Parownice": "czysciki-parowe",
                     "Myjki do okien": "myjki-do-okien", "Maszyny do szycia": "maszyny-do-szycia",
                     "Depilatory": "depilatory", "Golarki męskie": "golarki",
                     "Szczoteczki elektryczne": "szczoteczki-elektryczne",
                     "Ciśnieniomierze": "cisnieniomierze", "Lokówki": "lokowki",
                     "Suszarki do włosów": "suszarki-do-wlosow",
                     "Prostownice i karbownice": "prostownice-i-karbownice",
                     "Maszynki do strzyżenia": "maszynki-do-strzyzenia",
                     "Trymery": "trymery", "Alkomaty": "alkomaty", "Ekspresy ciśnieniowe": "ekspresy-cisnieniowe",
                     "Roboty kuchenne": "roboty-wieloczynnosciowe", "Sokowirówki": "sokowirowki",
                     "Wyciskarki wolnoobrotowe": "wyciskarki-wolnoobrotowe", "Blendery": "blendery",
                     "Blendery kielichowe": "blendery-kielichowe", "Czajniki elektryczne": "czajniki",
                     "Grille elektryczne": "grille", "Jajowary": "jajowary",
                     "Parowary": "parowary", "Miksery ręczne": "miksery-reczne",
                     "Opiekacze do kanapek": "sandwicze", "Oczyszczacze powietrza": "oczyszczacze-powietrza1",
                     "Nawilżacze powietrza": "nawilzacze-1", "Klimatyzatory przenośne": "klimatyzatory-przenosne1",
                     "Termowentylatory": "termowentylatory-1", "Grzejniki": "grzejniki-1",
                     "Elektroniczne nianie": "elektroniczne-nianie",
                     "Podgrzewacze do butelek": "podgrzewacze-do-butelek", "Laktatory": "laktatory",
                     "Wyposażenie do urządzeń kuchennych": "wyposazenie-do-robotow-kuchennych",
                     "Wkłady do dzbanków filtrujących": "wklady-do-dzbankow-filtrujacych",
                     "Filtry do ekspresów": "filtry-do-ekspresow",
                     "Worki i filtry do odkurzaczy": "worki-i-filtry-do-odkurzaczy",
                     "Folie i ostrza do golarek": "folie-i-ostrza-do-golarek",
                     "Końcówki do szczoteczek": "koncowki-do-szczoteczek"}

Komputery_url_dict = {"Laptopy i netbooki": "laptopy-i-netbooki", "Tablety": "ipad-i-tablety-multimedialne",
                      "Czytniki E-booków": "czytniki-ebookow", "Komputery stacjonarne": "komputery-stacjonarne-pc",
                      "Komputery All-In-One": "komputery-all-in-one", "Monitory": "monitory-led-i-lcd",
                      "Projektory multimedialne": "projektory-multimedialne",
                      "Dyski zewnętrzne": "dyski-twarde-zewnetrzne",
                      "Dyski SSD": "dyski-wewnetrzne-ssd", "Dyski sieciowe": "dyski-sieciowe",
                      "Pendrive": "pendrive-pamieci-usb", "Urządzenia wielofunkcyjne": "urzadzenia-wielofunkcyjne",
                      "Drukarki laserowe": "drukarki-laserowe", "Drukarki atramentowe": "drukarki-atramentowe",
                      "Niszczarki": "niszczarki", "Tusze i tonery": "tusze-i-tonery", "Routery": "routery",
                      "Modemy GSM": "modemy-gsm", "Routery GSM 3G": "routery-gsm-3g",
                      "Wzmacniacze sygnału Wi-Fi": "wzmacniacze-sygnalu-ac", "Karty sieciowe USB": "karty-sieciowe-usb",
                      "Anteny sieciowe": "anteny-sieciowe", "Myszki komputerowe": "myszy-komputerowe",
                      "Klawiatury komputerowe": "klawiatury-komputerowe",
                      "Zestawy mysz i klawiatura": "zestawy-mysz-i-klawiatura",
                      "Podkładki pod mysz": "podkladki-pod-mysz",
                      "Głośniki komputerowe": "glosniki-komputerowe",
                      "Słuchawki z mikrofonem": "sluchawki-z-mikrofonem",
                      "Kable komputerowe": "kable-i-adaptery-komputerowe", "Kamery internetowe": "kamery-internetowe",
                      "Tablety graficzne": "tablety-graficzne", "Torby do laptopów": "torby-do-laptopow",
                      "Akcesoria do laptopów (HUBy USB, Podkładki Chłodzące": "akcesoria-do-laptopow",
                      "Zasilacze do laptopów": "zasilacze-do-laptopow",
                      "Powerbanki": "ladowarki-akumulatory-przenosne2",
                      "Kontrolery do PC": "kontrolery-do-pc"}

Gry_i_konsole_url_dict = {"Konsole PlayStation 4": "konsole-playstation-4",
                          "Gry PS4": "gry-playstation-4",
                          "Akcesoria PlayStation 4": "akcesoria-playstation-4",
                          "Kontrolery PlayStation 4": "kontrolery-do-konsoli-playstation-4,h4",
                          "Gry PS3": "gry-playstation-3",
                          "Akcesoria PlayStation 3": "akcesoria-do-konsoli-playstation-3",
                          "Kontrolery PlayStation 3": "kontrolery-do-konsoli-playstation-3,h3",
                          "Konsole Xbox One": "konsole-xbox-one",
                          "Gry Xbox One": "gry-xbox-one", "Xbox Live": "xbox-live",
                          "Kontrolery Xbox One": "kontrolery-do-konsoli-xbox,h6",
                          "Akcesoria Xbox One": "akcesoria-xbox-one", "Konsole Xbox 360": "konsole-xbox-360",
                          "Gry Xbox 360": "gry-xbox-360", "Akcesoria Xbox 360": "akcesoria-do-konsoli-xbox",
                          "Kontrolery Xbox 360": "kontrolery-do-konsoli-xbox,h5", "Okulary VR": "okulary-vr",
                          "Słuchawki dla graczy": "sluchawki-z-mikrofonem,l1",
                          "Gry PC": "gry-pc", "Kontrolery do PC": "kontrolery-do-pc,h1",
                          "Kierownice PC": "kierownice-pc"}

Foto_i_kamery_url_dict = {"Lustrzanki": "lustrzanki", "Aparaty cyfrowe": "aparaty-cyfrowe",
                          "Aparaty natychmiastowe": "tradycyjne-aparaty-kompaktowe",
                          "Aparaty z wymienną optyką": "kompakty-z-wymienna-optyka", "Kamery 360": "kamery-360",
                          "Kamery sportowe": "kamery-sportowe", "Akcesoria do kamer sportowych": "akcesoria-do-kamer-sportowych",
                          "Kamery cyfrowe": "kamery", "Drony": "drony", "Akcesoria do dronów": "akcesoria-do-dronow",
                          "Lornetki": "lornetki", "Cyfrowe ramki do zdjęć": "cyfrowe-ramki-do-zdjec",
                          "Karty pamięci": "karty-pamieci", "Torby do aparatów i kamer": "torby", "Statywy": "statywy",
                          "Ładowarki": "ladowarki1", "Powerbanki": "ladowarki-akumulatory-przenosne"}

Telefony_i_GPS_url_dict = {"Telefony i Smartfony": "telefony-komorkowe", "Smartwatch": "smartwatch",
                           "Smartwatch Apple": "smartwatch,_Apple", "Zegarki sportowe": "zegarki-sportowe",
                           "Opaski monitorujące aktywność": "opaski-monitorujace-aktywnosc", "Tablety": "tablety2",
                           "Telefony bezprzewodowe": "telefony-bezprzewodowe", "Telefony przewodowe": "telefony-przewodowe",
                           "Krótkofalówki": "krotkofalowki", "Nawigacje samochodowe": "nawigacja-samochodowa-gps,g!nawigacja-samochodowa",
                           "Nawigacje ciężarowe": "nawigacja-samochodowa-gps,g!nawigacja-ciezarowa",
                           "Wideorejestratory": "rejestratory-jazdy", "Ładowarki samochodowe": "ladowarki-samochodowe1",
                           "Etui do telefonów": "etui-do-telefonow", "Zestawy słuchawkowe": "zestawy-sluchawkowe",
                           "Kable do telefonów": "kable-do-telefonow", "Ładowarki sieciowe": "ladowarki-sieciowe",
                           "Folie ochronne": "folie-ochronne", "Uchwyty do telefonów": "uchwyty-do-telefonow",
                           "Uchwyty do selfie": "uchwyty-do-selfie"}

