# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2017-09-09 19:30
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('euro', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='EuroAuchanNames',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('euro_name', models.CharField(max_length=100, verbose_name='Nazwa Euro: ')),
                ('auchan_name', models.CharField(max_length=100, verbose_name='Nazwa Auchan: ')),
                ('add_date', models.DateTimeField(verbose_name='Data dodania')),
            ],
            options={
                'verbose_name': 'Nazwa produktu',
                'verbose_name_plural': 'Nazwy produktów',
            },
        ),
        migrations.RemoveField(
            model_name='news',
            name='categories',
        ),
        migrations.DeleteModel(
            name='News',
        ),
    ]
