# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2017-09-10 20:32
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('euro', '0002_auto_20170909_2130'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='euroauchannames',
            name='add_date',
        ),
        migrations.AddField(
            model_name='euroauchannames',
            name='pol_num',
            field=models.CharField(default='POL0000000', max_length=10, verbose_name='Numer POL: '),
        ),
    ]
